# python -c "import toml;print( toml.load('config.toml'))"
# ALLOWED_BASH= ["/bin/bash","/bin/sh"]
# ALLOWED_POWERSHELL= ["powershell.exe","pwsh.exe"]
# ALLOWED_CMD= ["cmd.exe"]
# ALLOWED_DIRECTORIES = ['.']
COMMAND_TIMEOUT = 30
SAFETY_MODE = "strict"
# SAFETY_MODE = "relax"
IS_IN_DOCKER = false
HOST = "0.0.0.0"
PATH = "/shell"
PORT = 8002
# API_KEYS = "sk-1234"
API_KEYS = "sk-123456"

[DOCKER_CONFIG.windows]
work_dir = "/app/dev/repo"
host_root = "C:/Users/axdev/dev/repo"
# host_root = "."
allow_direcotories_host = [".", "C:/Users/axdev/dev/repo"]
allow_direcotories_docker = [".", "/tmp"]


[DOCKER_CONFIG.linux]
# work_dir = "/mnt/c/Users/axdev/dev/repo2"
work_dir = "/app/dev/repo"

host_root = "/mnt/c/Users/axdev/dev/repo"
# host_root = "."

allow_direcotories_host = ["."]
allow_direcotories_docker = [".", "/tmp"]


[TRUSTED_COMMANDS.t_pwd]
command = "pwd"
shell = "bash"
cwd = "./data"
description = "run pwd"

[TRUSTED_COMMANDS.t_ax_test]
command = """
pwd
apax test
"""
shell = "bash"
cwd = "C:/Users/axdev/dev/repo/ax-dev/myquickstart"
description = "run ax build"
