# python -c "import toml;print( toml.load('config.toml'))"
# ALLOWED_BASH= ["/bin/bash","/bin/sh"]
# ALLOWED_POWERSHELL= ["powershell.exe","pwsh.exe"]
# ALLOWED_CMD= ["cmd.exe"]
# ALLOWED_DIRECTORIES = ['.']
COMMAND_TIMEOUT = 60
SAFETY_MODE = "strict"
# SAFETY_MODE = "relax"
IS_IN_DOCKER = false

[DOCKER_CONFIG]
config_file = "docker/docker-compose.yml"
service = "drun1"

[DOCKER_CONFIG.windows]
work_dir = "/app/dev/repo2"
host_root = "C:/Users/axdev/dev/repo"
allow_direcotories_host = ["."]
allow_direcotories_docker = [".", "/tmp"]


[DOCKER_CONFIG.linux]
work_dir = "/mnt/c/Users/axdev/dev/repo2"
host_root = "/mnt/c/Users/axdev/dev/repo"
allow_direcotories_host = ["."]
allow_direcotories_docker = [".", "/tmp"]


[TRUSTED_COMMANDS]
uv_install = { command = "uv pip install .", shell = "bash", cwd = "." }
trusted_pwd = { command = "pwd", shell = "bash", cwd = "." }
